#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import os.path
import subprocess
from typing import NoReturn

HERE = os.path.abspath(os.path.dirname(__file__))
TOOLS = os.path.join(HERE, 'tools')
DOCKER_RUN = os.path.join(HERE, 'docker-run')

BUILDER_IMAGE = os.environ.get('DOCKERSHELF_BUILDER_IMAGE', 'dockershelf-python-builder')
ARCH = os.environ.get('DOCKERSHELF_ARCH', 'amd64')


def _gpg_volumes() -> list[str]:
    def _gpg(f: str, *, home: str = os.path.expanduser('~')) -> str:
        return os.path.join(home, '.gnupg', f)

    for paths in (
        ('pubring.kbx', 'private-keys-v1.d'),
        ('pubring.gpg', 'secring.gpg'),
    ):
        if all(os.path.exists(_gpg(p)) for p in paths):
            return [
                f'--volume={_gpg(p)}:{_gpg(p, home="/root")}:ro'
                for p in paths
            ]
    return []


def main() -> NoReturn:
    parser = argparse.ArgumentParser()
    parser.parse_args()

    print('*' * 79)
    print('Parsing target distribution')
    print('*' * 79)
    dist = subprocess.check_output((
        TOOLS, 'dpkg-parsechangelog', '--show-field=distribution',
    )).decode().strip()

    pwd = os.getcwd()
    dist_dir = os.path.abspath(os.path.join(pwd, '../python-pipeline/dist'))

    print('*' * 79)
    print(f'Running build for {ARCH} (results will be in {dist_dir})')
    print('*' * 79)
    os.makedirs(dist_dir, exist_ok=True)
    gbp_args = '-us -uc'
    gpg_setup = 'chmod 700 ~/.gnupg && ' if _gpg_volumes() else ''
    prog = (
        f'{gpg_setup}'
        f'apt-get update -qq && '
        f'cp -a /code /tmp/build-tree && '
        f'git config --global --add safe.directory /tmp/build-tree && '
        f'cd /tmp/build-tree && '
        f'apt-get build-dep -y -o Debug::pkgProblemResolver=yes . && '
        f'git clean -fxfd && '
        f'gbp buildpackage {gbp_args} --git-pristine-tar --git-debian-branch=debian/{dist} && '
        f'find .. -maxdepth 1 -type f -name "*.deb" | xargs --replace cp {{}} /dist'
    )
    cmd = (
        DOCKER_RUN,
        '--platform', f'linux/{ARCH}',
        *_gpg_volumes(),
        '-v', f'{pwd}:/code:ro',
        '-v', f'{dist_dir}:/dist:rw',
        f'{BUILDER_IMAGE}/{dist}', 'bash', '-euxc', prog,
    )
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    raise SystemExit(main())
