#!/usr/bin/env bash
# One-time (idempotent) APT repository setup on a Debian droplet.
#
# Run as root on the droplet:
#   curl -fsSL .../bootstrap-droplet.sh | bash
# or copy this directory and run:
#   DEPLOY_PUBLIC_KEY="$(cat dockershelf-deploy-ci.pub)" ./bootstrap-droplet.sh
#
# Environment:
#   DEPLOY_USER          deploy user name (default: deploy)
#   DEPLOY_PUBLIC_KEY    SSH public key for CI rsync/SSH (required)
#   DEPLOY_PUBLIC_KEY_FILE  path to public key file (alternative)
#   REPO_ROOT            /var/www/debian (default)
#   APT_HOSTNAME         apt.dockershelf.com (default)
#   SIGNWITH_KEY_ID      existing GPG key id for reprepro (optional; generates if unset)
#   SKIP_APT_INSTALL     set to 1 to skip apt-get install

set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
    echo "run as root" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DEPLOY_USER="${DEPLOY_USER:-deploy}"
REPO_ROOT="${REPO_ROOT:-/var/www/debian}"
INCOMING="${REPO_ROOT}/incoming"
APT_HOSTNAME="${APT_HOSTNAME:-apt.dockershelf.com}"
IMPORT_DEST="/usr/local/bin/dockershelf-import-incoming"
NGINX_SITE="/etc/nginx/sites-available/dockershelf-apt"

if [[ -n "${DEPLOY_PUBLIC_KEY_FILE:-}" ]]; then
    DEPLOY_PUBLIC_KEY="$(cat "$DEPLOY_PUBLIC_KEY_FILE")"
fi
if [[ -z "${DEPLOY_PUBLIC_KEY:-}" ]]; then
    echo "DEPLOY_PUBLIC_KEY or DEPLOY_PUBLIC_KEY_FILE is required" >&2
    exit 1
fi

if [[ "${SKIP_APT_INSTALL:-0}" != 1 ]]; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y reprepro nginx gnupg rsync
fi

if ! id "$DEPLOY_USER" &>/dev/null; then
    useradd -m -s /bin/bash "$DEPLOY_USER"
fi

mkdir -p "${REPO_ROOT}/conf" "${INCOMING}"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${REPO_ROOT}"

install -m 755 "${SCRIPT_DIR}/import-incoming.sh" "${IMPORT_DEST}"

# --- deploy user SSH ---
DEPLOY_HOME="$(getent passwd "$DEPLOY_USER" | cut -d: -f6)"
mkdir -p "${DEPLOY_HOME}/.ssh"
AUTH_KEYS="${DEPLOY_HOME}/.ssh/authorized_keys"
touch "$AUTH_KEYS"
if ! grep -qF "${DEPLOY_PUBLIC_KEY}" "$AUTH_KEYS" 2>/dev/null; then
    echo "$DEPLOY_PUBLIC_KEY" >> "$AUTH_KEYS"
fi
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${DEPLOY_HOME}/.ssh"
chmod 700 "${DEPLOY_HOME}/.ssh"
chmod 600 "$AUTH_KEYS"

# --- GPG signing key for reprepro Release files ---
GPG_HOME="${REPO_ROOT}/.gnupg"
if [[ -z "${SIGNWITH_KEY_ID:-}" ]]; then
    mkdir -p "$GPG_HOME"
    chmod 700 "$GPG_HOME"
    chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "$GPG_HOME"

    if ! sudo -u "$DEPLOY_USER" env GNUPGHOME="$GPG_HOME" \
        gpg --list-secret-keys --keyid-format long 2>/dev/null | grep -q '^sec'; then
        batch_file="${GPG_HOME}/keygen.batch"
        cat >"$batch_file" <<GPG
Key-Type: RSA
Key-Length: 4096
Subkey-Type: RSA
Subkey-Length: 4096
Name-Real: Dockershelf APT
Name-Email: apt@${APT_HOSTNAME}
Expire-Date: 5y
%no-protection
%commit
GPG
        chown "${DEPLOY_USER}:${DEPLOY_USER}" "$batch_file"
        sudo -u "$DEPLOY_USER" env GNUPGHOME="$GPG_HOME" gpg --batch --pinentry-mode loopback \
            --generate-key "$batch_file"
        rm -f "$batch_file"
    fi
    SIGNWITH_KEY_ID="$(sudo -u "$DEPLOY_USER" env GNUPGHOME="$GPG_HOME" \
        gpg --list-secret-keys --keyid-format long 2>/dev/null \
        | awk '/^sec/ {print $2}' | cut -d/ -f2 | head -1)"
fi

if [[ -z "$SIGNWITH_KEY_ID" ]]; then
    echo "could not determine SIGNWITH_KEY_ID" >&2
    exit 1
fi

sed "s/SIGNWITH_KEY_ID/${SIGNWITH_KEY_ID}/g" \
    "${SCRIPT_DIR}/reprepro-distributions" > "${REPO_ROOT}/conf/distributions"
chown "${DEPLOY_USER}:${DEPLOY_USER}" "${REPO_ROOT}/conf/distributions"

# --- nginx: serve repo under /dockershelf/ ---
cat > "${NGINX_SITE}" <<NGINX
# Dockershelf APT repository — generated by bootstrap-droplet.sh

server {
    listen 80;
    listen [::]:80;
    server_name ${APT_HOSTNAME};

    location /dockershelf/ {
        alias ${REPO_ROOT}/;
        autoindex off;
        limit_except GET HEAD {
            deny all;
        }
    }
}
NGINX

ln -sf "${NGINX_SITE}" /etc/nginx/sites-enabled/dockershelf-apt
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

PUBKEY_EXPORT="${REPO_ROOT}/dockershelf-apt-signing.pub"
sudo -u "$DEPLOY_USER" env GNUPGHOME="$GPG_HOME" \
    gpg --armor --export "$SIGNWITH_KEY_ID" > "$PUBKEY_EXPORT"
chown "${DEPLOY_USER}:${DEPLOY_USER}" "$PUBKEY_EXPORT"
chmod 644 "$PUBKEY_EXPORT"

cat <<EOF

Dockershelf APT repository bootstrap complete.

  Deploy user:     ${DEPLOY_USER}
  Repo root:       ${REPO_ROOT}
  Incoming:        ${INCOMING}
  reprepro SignWith: ${SIGNWITH_KEY_ID}
  Public APT URL:  http://${APT_HOSTNAME}/dockershelf/
  Signing pubkey:  ${PUBKEY_EXPORT}

Next steps:
  1. DNS A record: ${APT_HOSTNAME} -> this server's public IP
  2. TLS: certbot --nginx -d ${APT_HOSTNAME}
  3. GitHub: set DEPLOY_SSH_KEY and DEPLOY_* variables (see docs/deploy-setup.md)
  4. Client apt line (after TLS):
       deb [signed-by=/usr/share/keyrings/dockershelf.gpg] https://${APT_HOSTNAME}/dockershelf trixie main
  5. Copy signing key for image builds:
       scp ${DEPLOY_USER}@\$(hostname -I | awk '{print \$1}'):${PUBKEY_EXPORT} ./

EOF
